# -*- coding: utf8 -*-
import os
import sys
import glob
import multiprocessing

SetOption("num_jobs", multiprocessing.cpu_count()) # build with all available cpu cores/threads

env = Environment()
env.Decider("MD5")
conf = Configure(env)

if not conf.CheckLib('opencv4'):
    env.ParseConfig('pkg-config --cflags --libs opencv')
elif conf.CheckLib('opencv'):
    env.ParseConfig('pkg-config --cflags --libs opencv4')  # static build does not work anymore with default opencv ubuntu package
else:
    print("please install opencv4 or opencv")
    sys.exit(0)

env.Append(CXXFLAGS=['-std=c++11', "-O3", "-g"])

sources = set(glob.glob("*.cpp") + glob.glob("*.c"))

env.Program("siti", list(sources))

