# -*- coding: utf8 -*-
import os
import sys
import glob
import multiprocessing

SetOption("num_jobs", multiprocessing.cpu_count()) # build with all available cpu cores/threads

env = Environment()
env.Decider("MD5")
conf = Configure(env)

try:
    # default case for ubuntu 18.04
    env.ParseConfig('pkg-config --cflags --libs opencv')
except OSError as e:
    print("use opencv4")
    # case for ubuntu 20.04, 21.04
    env.ParseConfig('pkg-config --cflags --libs opencv4')


env.Append(CXXFLAGS=['-std=c++11', "-O3", "-g"])

sources = set(glob.glob("*.cpp") + glob.glob("*.c"))

env.Program("siti", list(sources))

